### PR TITLE
Update to 2.5.6

### PR DESCRIPTION
**Pull request by edamamez**

### CODE REVIEW

**Comment by yx-lamini** [comment]
https://github.com/lamini-ai/lamini-examples/pull/100
Merged and tested against 2.5.6; should be OK to merge now.

**Comment by yx-lamini** [comment]
https://github.com/lamini-ai/lamini-examples/actions/runs/10070726103
The tests are failing, seems the branch needs to be resynced with main.

**Comment by edamamez** [comment]
Just rebased and looks like there's a new issue with RAG: https://github.com/lamini-ai/lamini-examples/actions/runs/10082793510/job/27877858314

**Comment by yx-lamini** [comment]
https://github.com/lamini-ai/lamini-examples/pull/103
Merged and tested, this time all examples in the workflow should pass.

**Comment by edamamez** [comment]
Passes now!! Thank you so much for your work 🙇 

https://github.com/lamini-ai/lamini-examples/actions/runs/10116053247

**Pull request merged**
